---

version: "3.7"

services:
  ldap:
    image: osixia/openldap:stable
    environment:
        LDAP_ORGANISATION: "oreno-company"
        LDAP_DOMAIN: "my-company.com"
        LDAP_ADMIN_PASSWORD: "password"

  ldap-phpadmin:
    image: osixia/phpldapadmin:stable
    environment:
        PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
        - "443:443"
